# Sample folder structure

# ./
#  .pandoc_style.css   <- hidden CSS style file
#  report.html         <- generated by pandoc
#  src/
#   00_header.md       <- md files
#   01_part.md
#   02_part.md
#   03_footer.md
#   img/               <- images and their sources
#    image_1.png
#    image_1.xml
#    image_2.png
#    image_2.svgz


#################### DEFINITIONS #######################
TARGET := pipeline_topology
CSS := .pandoc_style.css
BROWSER := firefox

.PHONY: watch

all: html

html: FORMAT = html
docx: FORMAT = docx
pdf:  FORMAT = pdf
	ENGINE = --pdf-engine wkhtmltopdf

# User-created MD files
MD := $(filter %.md, $(wildcard src/*))
MD := $(sort $(MD))
MD_HERE := $(patsubst src/%, %, $(MD))


#################### RULES #######################
watch:
	while true; do \
		inotifywait -qr -e modify -e create -e delete -e move src; \
		make all; \
	done

# Call pandoc to convert the files
html docx pdf: $(CSS) $(MD) src/metadata.yaml $(FORMAT)
	cd src && /usr/bin/pandoc -s --verbose --self-contained --css ../$< \
	  -V date="$(shell date +%Y-%m-%d%n)" \
	  metadata.yaml $(ENGINE) \
	  $(MD_HERE) -o ../$(TARGET).$(FORMAT)

clean:
	rm -f $(TARGET).html $(TARGET).docx

