# Sample folder structure

# ./
#  .pandoc_style.css   <- hidden CSS style file
#  report.html         <- generated by pandoc
#  src/
#   00_header.md       <- md files
#   01_part.md
#   02_part.md
#   03_footer.md
#   img/               <- images and their sources
#    image_1.png
#    image_1.xml
#    image_2.png
#    image_2.svgz


#################### DEFINITIONS #######################
NAME := report
CSS := .pandoc_style.css
TARGET := $(NAME).html

all: $(TARGET)

# User-created MD files
MD := $(filter %.md, $(wildcard src/*))
MD := $(sort $(MD))
MD_HERE := $(patsubst src/%, %, $(MD))


#################### RULES #######################
all: $(TARGET)

# create the main HTML file
$(TARGET): $(CSS) $(MD)
	cd src && pandoc -s --self-contained --css ../$< $(MD_HERE) -o $@
	mv src/$@ $@

clean:
	rm -f $(TARGET)
